### ISSUE TITLE
Plugin for editor?

### ISSUE THREAD

**Issue by Alexey-T** [ueffel/Keypirinha-PackageControl#10]
Hi, sorry that I post in this repo.
You liked one of my repos. Don't you want to make a Python plugin for CudaText? I have idea for some useful plugin (related to LSP). Are you interested?

**Comment by ueffel** [comment]
Hi,

sounds interesting, yeah sure I would give it a try.

**Comment by Alexey-T** [comment]
Ok. There is LSP, to use 3rd party autocompletion servers in CudaText
https://langserver.org/
I am interested in plugin which supports LSP in Cud. The plugin API allows to show autocompletion lists, docs; 
https://wiki.freepascal.org/CudaText_API#Editor.complete
It is not easy plugin.

**Comment by Alexey-T** [comment]
I will help with testing (and with any plugin API) of course.

**Comment by ueffel** [comment]
@Alexey-T I'm sorry, I don't think I will find the time for this plugin in the near future. You should look out for another Developer for this. Again: Sorry.
