### ISSUE TITLE
Kill package is not listed

### ISSUE THREAD

**Issue by sschuberth** [ueffel/Keypirinha-PackageControl#13]
Even after updating the repository list, the [Kill package / plugin](https://github.com/ueffel/Keypirinha-Plugin-Kill) which *is* listed [here](https://ue.spdns.de/packagecontrol/) is not found by the package install command when entering "kill" as a search string. Also using the full string "Keypirinha-Plugin-Kill" as noted [here](https://github.com/ueffel/Keypirinha-Plugin-Kill#installation) does not work. Any idea why that is?

**Comment by ueffel** [comment]
Do you have it already installed by chance? The install command only lists packages that are not installed already. You could use the `PackageControl: Remove Package` (which only lists installed packages) to check.
Or maybe it is already installed, but not through PackageControl (untracked package), then try `PackageControl: Reinstall untracked package from repository`

**Comment by sschuberth** [comment]
> Do you have it already installed by chance?

My bad, you're right 🙄 I must have installed it too long ago to remember. Sorry for the noise!
