### ISSUE TITLE
Server-side repository?

### ISSUE THREAD

**Issue by polyvertex** [ueffel/Keypirinha-PackageControl#7]
As mentioned in https://github.com/Keypirinha/Keypirinha/issues/71#issuecomment-437453190 and in case you are willing to share, it might be a good idea create a repo dedicated to the server-side - or just a folder into this repo I don't know - so that users could provide PRs already?

I for one would be interested (e.g. #6)

**Comment by ueffel** [comment]
It's on my list of things to do. The code is not in a state to release to the public.
The server side will be a separate github repository, when it's ready.
